name: Pull Request

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: earthly --ci +lint
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        base-image:
          - quay.io/kairos/core-opensuse:v1.0.0-rc2
          - quay.io/kairos/core-opensuse:latest
          - quay.io/kairos/core-ubuntu:latest
        rke2-version:
          - v1.25.0+rke2r1
          - v1.24.4+rke2r1
          - v1.23.10+rke2r1
          - v1.22.13+rke2r1
        platform:
          - linux/amd64
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: earthly --ci --platform=${{ matrix.platform }} +docker --RKE2_VERSION=${{ matrix.rke2-version }} --BASE_IMAGE=${{ matrix.base-image }}
